task.defer(function()
local name = {
    ["JX-CRIMINALITY"] = "JX犯罪",
    ["Dsc.gg/getjx"] = "Discord获取",
    ["Aims"] = "瞄准",
    ["Players"] = "玩家",
    ["Mods"] = "模组",
    ["Visual"] = "视觉",
    ["Misc"] = "杂项",
    ["Settings"] = "设置",
    ["Silent Aim"] = "子弹追踪",
    ["None"] = "开关",
    ["Show FOV Circle"] = "显示FOV圆圈",
    ["Circle Center Only (MOBILE)"] = "仅圆圈（移动端）",
    ["FOV Size"] = "FOV大小",
    ["Max Distance (Studs)"] = "最大距离（单位）",
    ["Check Wall"] = "穿墙检测",
    ["Use HitChance"] = "使用命中率",
    ["HitChance %"] = "命中率百分比",
    ["Target Part"] = "目标部位",
    ["Head"] = "头部",
    ["Target Change Time"] = "目标切换时间",
    ["Check Downed"] = "检测倒地",
    ["Hit Part Notification"] = "命中部位提示",
    ["Notification Size"] = "提示大小",
    ["Team Check"] = "队伍检测",
    ["Rage Bot"] = "狂暴模式",
    ["Use FOV Circle"] = "使用FOV圆圈",
    ["Shoot Speed (Less = Fast)"] = "射击速度（值越小越快）",
    ["Hit Distance"] = "命中距离",
    ["AimBot"] = "自瞄",
    ["Aimbot"] = "自瞄",
    ["Lock KeyBind"] = "锁定按键",
    ["MouseButton2"] = "鼠标右键",
    ["Save Lock Key"] = "保存锁定键",
    ["Lock Method"] = "锁定方式",
    ["Hold"] = "按住",
    ["Prediction"] = "预测",
    ["Wall Check"] = "穿墙检测",
    ["Show FOV"] = "显示FOV",
    ["Circle Center Only (Mobile)"] = "仅圆心（移动端）",
    ["Lock Part"] = "锁定部位",
    ["Random Change Time"] = "随机切换时间",
    ["Circle Button (Mobile)"] = "圆圈按钮（移动端）",
    ["Circle Size"] = "圆圈大小",
    ["Circle X Position"] = "圆圈X位置",
    ["Circle Y Position"] = "圆圈Y位置",
    ["Player"] = "玩家",
    ["Fast Pickup"] = "快速拾取",
    ["Infinite Stamina"] = "无限耐力",
    ["No Fail Lockpick"] = "开锁必成",
    ["Noclip"] = "穿墙模式",
    ["CTRL + CLICK = TP"] = "CTRL+点击=传送",
    ["Q = TP to Mouse"] = "Q=传送到鼠标位置",
    ["Chat Enabler"] = "聊天启用",
    ["FLY & SPEED"] = "飞行与速度",
    ["Speed"] = "速度",
    ["Speed Multiplier"] = "速度倍率",
    ["Fly"] = "飞行",
    ["Fly Speed"] = "飞行速度",
    ["Fly Method"] = "飞行方式",
    ["Bypass"] = "绕过",
    ["Anti"] = "反制",
    ["Anti Smoke"] = "防烟雾",
    ["Anti Fall Damage"] = "防坠落伤害",
    ["Anti Barriers"] = "防障碍",
    ["Anti Neck Movement"] = "防颈部移动",
    ["Anti AFK"] = "防挂机",
    ["Auto"] = "自动",
    ["Auto Pick Up Tool"] = "自动拾取工具",
    ["Auto Pick Up Cash"] = "自动拾取现金",
    ["Auto UnLock Door"] = "自动解锁门",
    ["Auto Open Doors"] = "自动开门",
    ["Auto Respawn"] = "自动重生",
    ["AutoFarm Allowance (Claim)"] = "自动收割许可(签到)",
    ["Gun"] = "枪械",
    ["Bullet Tracer"] = "子弹轨迹",
    ["Wall Bang"] = "穿墙射击",
    ["Instant Equip"] = "瞬间装备",
    ["Instant Reload"] = "瞬间换弹",
    ["No Recoil"] = "无后坐力",
    ["Melee Aura"] = "拳头光环",
    ["Show Animation"] = "显示动画",
    ["Melee Aura Distance"] = "近战光环距离",
    ["Spray Mods"] = "喷涂模组",
    ["Infinite Pepper Spray"] = "无限胡椒喷雾",
    ["Pepper Spray Aura"] = "胡椒喷雾光环",
    ["Pepper Spray Aura Range"] = "胡椒喷雾范围",
    ["Control"] = "控制",
    ["C4 Control"] = "C4控制",
    ["C4 Speed"] = "C4速度",
    ["Rocket Control"] = "火箭控制",
    ["Rocket Speed"] = "火箭速度",
    ["ESP"] = "透视",
    ["Player Detect If Near"] = "玩家接近检测",
    ["Arms Chams"] = "手臂上色",
    ["ESP BOX"] = "透视方框",
    ["ESP HIGHLIGHT"] = "透视高亮",
    ["ESP NAME"] = "透视名称",
    ["ESP HEALTH"] = "透视生命值",
    ["ESP HEALTH BAR"] = "透视血条",
    ["ESP TOOL"] = "透视工具",
    ["ESP DISTANCE"] = "透视距离",
    ["ESP TEAM CHECK"] = "透视队伍检测",
    ["ESP TRACER"] = "透视轨迹",
    ["Tracer Position"] = "轨迹位置",
    ["Bottom"] = "底部",
    ["In-Game ESP"] = "游戏内透视",
    ["ESP Safe/Register"] = "透视保险箱/收银机",
    ["ESP Pile (Scrap, Crates)"] = "透视堆（废料、箱子）",
    ["ESP ATM"] = "透视ATM",
    ["ESP Dealer"] = "透视商人",
    ["World"] = "世界",
    ["Delete All Doors"] = "删除所有门",
    ["Full Bright"] = "全亮",
    ["Admin Check"] = "管理员检测",
    ["FOV"] = "视野",
    ["Camera Distance"] = "摄像机距离",
    ["FUN"] = "娱乐",
    ["Hug Tool"] = "拥抱工具",
    ["Jerk Tool"] = "抽搐工具",
    ["Carpet Tool"] = "地毯工具",
    ["Fake-Downed Tool"] = "假死工具",
    ["Hide head"] = "隐藏头部",
    ["Menu"] = "菜单",
    ["Open Keybind Menu"] = "打开按键绑定菜单",
    ["Custom Cursor"] = "自定义光标",
    ["Notification Side"] = "提示位置",
    ["Right"] = "右侧",
    ["DPI Scale"] = "DPI缩放",
    ["Menu Keybind"] = "菜单按键",
    ["RightAlt"] = "右Alt",
    ["Unload Script"] = "卸载脚本",
    ["Themes"] = "主题",
    ["Background color"] = "背景颜色",
    ["Main color"] = "主色",
    ["Accent color"] = "强调色",
    ["Outline color"] = "轮廓色",
    ["Font color"] = "字体颜色",
    ["Font Face"] = "字体",
    ["Code"] = "代码",
    ["Theme list"] = "主题列表",
    ["Default"] = "默认",
    ["Set as default"] = "设为默认",
    ["Custom theme name"] = "自定义主题名称",
    ["Create theme"] = "创建主题",
    ["Custom themes"] = "自定义主题",
    ["Load theme"] = "加载主题",
    ["Overwrite theme"] = "覆盖主题",
    ["Delete theme"] = "删除主题",
    ["Refresh list"] = "刷新列表",
    ["Reset default"] = "重置默认",
    ["Configuration"] = "配置",
    ["Config name"] = "配置名称",
    ["Create config"] = "创建配置",
    ["Config list"] = "配置列表",
    ["Load config"] = "加载配置",
    ["Overwrite config"] = "覆盖配置",
    ["Delete config"] = "删除配置",
    ["Set as autoload"] = "设为自动加载",
    ["Reset autoload"] = "重置自动加载",
    ["Current autoload config: none"] = "当前自动加载配置：无",
    ["JX"] = "JX",
    ["Toggle"] = "切换",
    ["Random"] = "随机",
    ["HumanoidRootPart"] = "人物根部位",
    ["Left Arm"] = "左臂",
    ["Right Arm"] = "右臂",
    ["Left Leg"] = "左腿",
    ["Right Leg"] = "右腿",
    ["Torso"] = "躯干",
    ["Velocity"] = "速度",
    ["Tracer Color"] = "轨迹颜色",
    ["Copy color"] = "复制颜色",
    ["Paste color"] = "粘贴颜色",
    ["Copy Hex"] = "复制Hex",
    ["Copy RGB"] = "复制RGB",
    ["Top"] = "顶部",
    ["Middle"] = "中部",
    ["Mouse"] = "鼠标",
    ["Left"] = "左侧",
    ["Always"] = "总是",
    ["BuilderSans"] = "Builder Sans",
    ["Fantasy"] = "幻想",
    ["Gotham"] = "哥谭",
    ["Jura"] = "Jura",
    ["Roboto"] = "Roboto",
    ["RobotoMono"] = "Roboto Mono",
    ["SourceSans"] = "Source Sans",
    ["BBot"] = "BBot",
    ["Fatality"] = "致命",
    ["Jester"] = "小丑",
    ["Mint"] = "薄荷",
    ["Tokyo Night"] = "东京之夜",
    ["Ubuntu"] = "Ubuntu",
    ["Quartz"] = "石英",
    ["Nord"] = "Nord",
    ["Dracula"] = "德古拉",
    ["Monokai"] = "Monokai",
    ["Gruvbox"] = "Gruvbox",
    ["Solarized"] = "Solarized",
    ["Catppuccin"] = "Catppuccin",
    ["One Dark"] = "One Dark",
    ["Cyberpunk"] = "赛博朋克",
    ["Oceanic Next"] = "Oceanic Next",
    ["Material"] = "Material"
}
    while true do
        task.wait(0.5)
        local coreGui = game:GetService("CoreGui")
        local obsidianUI = coreGui:FindFirstChild("Obsidian")
        if not obsidianUI then continue end

        local main = obsidianUI:FindFirstChild("Main")
        if not main then continue end
        
        local children = main:GetChildren()
        if #children < 6 then continue end
        
        local child6 = children[6]
        
        local frame = child6:FindFirstChild("Frame")
        if not frame then continue end
        
        local textLabel = frame:FindFirstChild("TextLabel")
        if not textLabel then continue end
        
        textLabel.Text = "大司马脚本 | 犯罪"

        for _, descendant in ipairs(obsidianUI:GetDescendants()) do
            if (descendant:IsA("TextLabel") or descendant:IsA("TextButton") or descendant:IsA("TextBox")) then
                descendant.Text = name[descendant.Text] or descendant.Text
            end
        end
    end
end)
task.wait()
getgenv().gethui = nil
loadstring(game:HttpGet("https://raw.githubusercontent.com/lyyanai/crim/refs/heads/main/jx"))()